// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "auth/auth.proto" (package "keyfi_protos.auth", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AuthenticationService } from "./auth";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { AuthResponse } from "./auth";
import type { AuthRequest } from "./auth";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service keyfi_protos.auth.AuthenticationService
 */
export interface IAuthenticationServiceClient {
    /**
     * @generated from protobuf rpc: Login(keyfi_protos.auth.AuthRequest) returns (keyfi_protos.auth.AuthResponse);
     */
    login(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, AuthResponse>;
    /**
     * @generated from protobuf rpc: Register(keyfi_protos.auth.AuthRequest) returns (keyfi_protos.auth.AuthResponse);
     */
    register(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, AuthResponse>;
}
/**
 * @generated from protobuf service keyfi_protos.auth.AuthenticationService
 */
export class AuthenticationServiceClient implements IAuthenticationServiceClient, ServiceInfo {
    typeName = AuthenticationService.typeName;
    methods = AuthenticationService.methods;
    options = AuthenticationService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: Login(keyfi_protos.auth.AuthRequest) returns (keyfi_protos.auth.AuthResponse);
     */
    login(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, AuthResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Register(keyfi_protos.auth.AuthRequest) returns (keyfi_protos.auth.AuthResponse);
     */
    register(input: AuthRequest, options?: RpcOptions): UnaryCall<AuthRequest, AuthResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<AuthRequest, AuthResponse>("unary", this._transport, method, opt, input);
    }
}
