// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "keyFiAI.proto" (package "keyfiai", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { KeyFiAIService } from "./keyFiAI";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SinglePromptResponse } from "./keyFiAI";
import type { SinglePromptRequest } from "./keyFiAI";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service keyfiai.KeyFiAIService
 */
export interface IKeyFiAIServiceClient {
    /**
     * @generated from protobuf rpc: SinglePrompt(keyfiai.SinglePromptRequest) returns (keyfiai.SinglePromptResponse);
     */
    singlePrompt(input: SinglePromptRequest, options?: RpcOptions): UnaryCall<SinglePromptRequest, SinglePromptResponse>;
}
/**
 * @generated from protobuf service keyfiai.KeyFiAIService
 */
export class KeyFiAIServiceClient implements IKeyFiAIServiceClient, ServiceInfo {
    typeName = KeyFiAIService.typeName;
    methods = KeyFiAIService.methods;
    options = KeyFiAIService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SinglePrompt(keyfiai.SinglePromptRequest) returns (keyfiai.SinglePromptResponse);
     */
    singlePrompt(input: SinglePromptRequest, options?: RpcOptions): UnaryCall<SinglePromptRequest, SinglePromptResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SinglePromptRequest, SinglePromptResponse>("unary", this._transport, method, opt, input);
    }
}
