// @generated by protobuf-ts 2.9.4 with parameter long_type_string
// @generated from protobuf file "ai/ai.proto" (package "keyfi_protos.ai", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { AIService } from "./ai";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { SinglePromptResponse } from "./ai";
import type { SinglePromptRequest } from "./ai";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * @generated from protobuf service keyfi_protos.ai.AIService
 */
export interface IAIServiceClient {
    /**
     * @generated from protobuf rpc: SinglePrompt(keyfi_protos.ai.SinglePromptRequest) returns (keyfi_protos.ai.SinglePromptResponse);
     */
    singlePrompt(input: SinglePromptRequest, options?: RpcOptions): UnaryCall<SinglePromptRequest, SinglePromptResponse>;
}
/**
 * @generated from protobuf service keyfi_protos.ai.AIService
 */
export class AIServiceClient implements IAIServiceClient, ServiceInfo {
    typeName = AIService.typeName;
    methods = AIService.methods;
    options = AIService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * @generated from protobuf rpc: SinglePrompt(keyfi_protos.ai.SinglePromptRequest) returns (keyfi_protos.ai.SinglePromptResponse);
     */
    singlePrompt(input: SinglePromptRequest, options?: RpcOptions): UnaryCall<SinglePromptRequest, SinglePromptResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<SinglePromptRequest, SinglePromptResponse>("unary", this._transport, method, opt, input);
    }
}
