// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v5.26.1
// source: protos/keyFiAI.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	KeyFiAIService_SinglePrompt_FullMethodName = "/keyfiai.KeyFiAIService/SinglePrompt"
)

// KeyFiAIServiceClient is the client API for KeyFiAIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyFiAIServiceClient interface {
	SinglePrompt(ctx context.Context, in *SinglePromptRequest, opts ...grpc.CallOption) (*SinglePromptResponse, error)
}

type keyFiAIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyFiAIServiceClient(cc grpc.ClientConnInterface) KeyFiAIServiceClient {
	return &keyFiAIServiceClient{cc}
}

func (c *keyFiAIServiceClient) SinglePrompt(ctx context.Context, in *SinglePromptRequest, opts ...grpc.CallOption) (*SinglePromptResponse, error) {
	out := new(SinglePromptResponse)
	err := c.cc.Invoke(ctx, KeyFiAIService_SinglePrompt_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyFiAIServiceServer is the server API for KeyFiAIService service.
// All implementations must embed UnimplementedKeyFiAIServiceServer
// for forward compatibility
type KeyFiAIServiceServer interface {
	SinglePrompt(context.Context, *SinglePromptRequest) (*SinglePromptResponse, error)
	mustEmbedUnimplementedKeyFiAIServiceServer()
}

// UnimplementedKeyFiAIServiceServer must be embedded to have forward compatible implementations.
type UnimplementedKeyFiAIServiceServer struct {
}

func (UnimplementedKeyFiAIServiceServer) SinglePrompt(context.Context, *SinglePromptRequest) (*SinglePromptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SinglePrompt not implemented")
}
func (UnimplementedKeyFiAIServiceServer) mustEmbedUnimplementedKeyFiAIServiceServer() {}

// UnsafeKeyFiAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyFiAIServiceServer will
// result in compilation errors.
type UnsafeKeyFiAIServiceServer interface {
	mustEmbedUnimplementedKeyFiAIServiceServer()
}

func RegisterKeyFiAIServiceServer(s grpc.ServiceRegistrar, srv KeyFiAIServiceServer) {
	s.RegisterService(&KeyFiAIService_ServiceDesc, srv)
}

func _KeyFiAIService_SinglePrompt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SinglePromptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyFiAIServiceServer).SinglePrompt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyFiAIService_SinglePrompt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyFiAIServiceServer).SinglePrompt(ctx, req.(*SinglePromptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyFiAIService_ServiceDesc is the grpc.ServiceDesc for KeyFiAIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyFiAIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keyfiai.KeyFiAIService",
	HandlerType: (*KeyFiAIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SinglePrompt",
			Handler:    _KeyFiAIService_SinglePrompt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/keyFiAI.proto",
}
